# Generated by Django 3.2.25 on 2026-05-28 04:36

import discordoauth2.managers
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('display_name', models.CharField(max_length=25, null=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator(), django.core.validators.MinLengthValidator(4)], verbose_name='display name')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='user id')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('discriminator', models.CharField(max_length=4, verbose_name='discriminator')),
                ('avatar', models.URLField(verbose_name='avatar')),
                ('public_flags', models.IntegerField(verbose_name='public flags')),
                ('flags', models.IntegerField(verbose_name='flags')),
                ('locale', models.CharField(max_length=100, verbose_name='locale')),
                ('mfa_enabled', models.BooleanField(verbose_name='multi-factor authentication enabled')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('verified', models.BooleanField(help_text='Whether the user has verified their email address.', verbose_name='email verified')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', discordoauth2.managers.DiscordUserOAuth2Manager()),
            ],
        ),
    ]
