# Generated by Django 3.2.25 on 2026-05-28 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionshipPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=25)),
                ('event_1', models.IntegerField(default=0)),
                ('event_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=25)),
                ('ranking_points', models.IntegerField()),
                ('time_set', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=25)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('match_type', models.CharField(choices=[('q', 'Qualifications'), ('qf', 'Quarterfinals'), ('sf', 'Semifinals'), ('f', 'Finals')], default='q', max_length=2)),
                ('red1', models.CharField(max_length=25)),
                ('red2', models.CharField(max_length=25)),
                ('red3', models.CharField(max_length=25)),
                ('blue1', models.CharField(max_length=25)),
                ('blue2', models.CharField(max_length=25)),
                ('blue3', models.CharField(max_length=25)),
                ('red1_redcard', models.BooleanField(default=False)),
                ('red2_redcard', models.BooleanField(default=False)),
                ('red3_redcard', models.BooleanField(default=False)),
                ('blue1_redcard', models.BooleanField(default=False)),
                ('blue2_redcard', models.BooleanField(default=False)),
                ('blue3_redcard', models.BooleanField(default=False)),
                ('red1_surrogate', models.BooleanField(default=False)),
                ('red2_surrogate', models.BooleanField(default=False)),
                ('red3_surrogate', models.BooleanField(default=False)),
                ('blue1_surrogate', models.BooleanField(default=False)),
                ('blue2_surrogate', models.BooleanField(default=False)),
                ('blue3_surrogate', models.BooleanField(default=False)),
                ('red1_contribution', models.IntegerField(blank=True, null=True)),
                ('red2_contribution', models.IntegerField(blank=True, null=True)),
                ('red3_contribution', models.IntegerField(blank=True, null=True)),
                ('blue1_contribution', models.IntegerField(blank=True, null=True)),
                ('blue2_contribution', models.IntegerField(blank=True, null=True)),
                ('blue3_contribution', models.IntegerField(blank=True, null=True)),
                ('red_score', models.IntegerField(blank=True, null=True)),
                ('red_climb_rp', models.BooleanField(blank=True, null=True)),
                ('red_wheel_rp', models.BooleanField(blank=True, null=True)),
                ('red_auto_points', models.IntegerField(blank=True, null=True)),
                ('red_teleop_points', models.IntegerField(blank=True, null=True)),
                ('red_endgame_points', models.IntegerField(blank=True, null=True)),
                ('red_power_cells', models.IntegerField(blank=True, null=True)),
                ('blue_score', models.IntegerField(blank=True, null=True)),
                ('blue_climb_rp', models.BooleanField(blank=True, null=True)),
                ('blue_wheel_rp', models.BooleanField(blank=True, null=True)),
                ('blue_auto_points', models.IntegerField(blank=True, null=True)),
                ('blue_teleop_points', models.IntegerField(blank=True, null=True)),
                ('blue_endgame_points', models.IntegerField(blank=True, null=True)),
                ('blue_power_cells', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='ElimsAlliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance_number', models.IntegerField(blank=True, null=True)),
                ('player1', models.CharField(max_length=25)),
                ('player2', models.CharField(max_length=25)),
                ('player3', models.CharField(max_length=25)),
                ('advancement', models.CharField(choices=[('qf', 'QF'), ('sf', 'SF'), ('f', 'F'), ('w', 'W')], default='qf', max_length=25)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
