# Generated by Django 3.1.5 on 2021-01-22 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210121_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='Rankings',
            new_name='Ranking',
        ),
    ]
