# Generated by Django 3.1.5 on 2021-02-01 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_championshippoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championshippoints',
            name='event',
        ),
    ]
