# Generated by Django 3.1.5 on 2021-01-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_match_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='blue_climb_rp',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_wheel_rp',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red_climb_rp',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red_wheel_rp',
            field=models.BooleanField(null=True),
        ),
    ]
