# Generated by Django 3.1.5 on 2021-01-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210127_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElimsAlliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance_number', models.IntegerField(blank=True, null=True)),
                ('player1', models.CharField(max_length=25)),
                ('player2', models.CharField(max_length=25)),
                ('player3', models.CharField(max_length=25)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
