# Generated by Django 3.1.5 on 2021-01-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_elimsalliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='elimsalliance',
            name='advancement',
            field=models.CharField(choices=[('qf', 'QF'), ('sf', 'SF'), ('f', 'F'), ('w', 'W')], default='qf', max_length=25),
        ),
    ]
