# Generated by Django 3.1.5 on 2021-02-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_elimsalliance_advancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='blue1_contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='blue1_redcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='blue1_surrogate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='blue2_contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='blue2_redcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='blue2_surrogate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='blue3_contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='blue3_redcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='blue3_surrogate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_auto_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_endgame_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_power_cells',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_teleop_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red1_contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red1_redcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='red1_surrogate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='red2_contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red2_redcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='red2_surrogate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='red3_contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red3_redcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='red3_surrogate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='red_auto_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red_endgame_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red_power_cells',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red_teleop_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='blue_climb_rp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='blue_wheel_rp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='red_climb_rp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='red_wheel_rp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
