# Generated by Django 3.2.25 on 2026-05-28 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExemptedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('robot', models.CharField(max_length=25)),
                ('game', models.CharField(max_length=25)),
                ('game_slug', models.CharField(max_length=5)),
                ('auto_or_teleop', models.CharField(default='TELE', max_length=4)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('time_set', models.DateTimeField(auto_now_add=True)),
                ('source', models.URLField()),
                ('approved', models.BooleanField(default=False)),
                ('clean_code', models.CharField(max_length=4000)),
                ('decrypted_code', models.CharField(blank=True, max_length=2000, null=True)),
                ('client_version', models.CharField(blank=True, max_length=20, null=True)),
                ('time_of_score', models.CharField(blank=True, max_length=30, null=True)),
                ('robot_position', models.CharField(blank=True, max_length=20, null=True)),
                ('time_data', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highscores.leaderboard')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CleanCodeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_code', models.CharField(max_length=600)),
                ('score', models.IntegerField()),
                ('time_set', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highscores.leaderboard')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['leaderboard'], name='highscores__leaderb_ad4364_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['player'], name='highscores__player__3776b0_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['approved'], name='highscores__approve_054a97_idx'),
        ),
    ]
