# Generated by Django 3.1.5 on 2021-01-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0002_score_time_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time_set',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
