# Generated by Django 3.1.5 on 2021-01-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0005_auto_20210114_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='source',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
