# Generated by Django 3.1.5 on 2021-01-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0006_score_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='clean_code',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
