# Generated by Django 3.1.5 on 2021-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0007_score_clean_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='game_settings',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
