# Generated by Django 3.1.5 on 2021-01-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0009_auto_20210124_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanCodeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_code', models.CharField(max_length=400)),
            ],
        ),
    ]
