# Generated by Django 3.1.5 on 2021-01-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0010_cleancodesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleancodesubmission',
            name='player_name',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
