# Generated by Django 3.2.25 on 2026-05-28 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('launching', 'Launching'), ('running', 'Running'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('expired', 'Expired'), ('killed', 'Killed')], default='running', max_length=16)),
                ('requested_minutes', models.PositiveIntegerField()),
                ('allocated_minutes', models.PositiveIntegerField()),
                ('game', models.CharField(blank=True, max_length=80)),
                ('game_code', models.CharField(blank=True, max_length=32)),
                ('comment', models.CharField(blank=True, max_length=120)),
                ('server_identifier', models.CharField(blank=True, max_length=128)),
                ('orchestrator_session_id', models.CharField(blank=True, max_length=128)),
                ('orchestrator_state', models.CharField(blank=True, max_length=64)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('server_password', models.CharField(blank=True, max_length=80)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('orchestrator_stopped_at', models.DateTimeField(blank=True, null=True)),
                ('launch_error_code', models.CharField(blank=True, max_length=80)),
                ('launch_error_message', models.TextField(blank=True)),
                ('launch_context', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('polar', 'Polar'), ('discord_server_subscription', 'Discord Server Subscription'), ('github_sponsors', 'GitHub Sponsors'), ('comp', 'Comp')], max_length=40)),
                ('provider_customer_id', models.CharField(blank=True, max_length=128)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('inactive', 'Inactive')], default='active', max_length=24)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('latest_event_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.SlugField(help_text='Stable plan identifier used in checkout URLs, Polar metadata, and API responses.', max_length=64, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('benefit_lines', models.TextField(blank=True, help_text='Optional website benefit copy, one benefit per line.')),
                ('monthly_price_usd', models.PositiveIntegerField()),
                ('monthly_server_minutes', models.PositiveIntegerField()),
                ('max_session_minutes', models.PositiveIntegerField()),
                ('max_concurrent_servers', models.PositiveIntegerField(default=1)),
                ('polar_product_id', models.CharField(blank=True, max_length=128)),
                ('discord_role_id', models.CharField(blank=True, max_length=64)),
                ('entitlement_priority', models.IntegerField(default=0, help_text='Higher priority wins when a user has multiple active entitlements.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'monthly_price_usd', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UsageLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_start', models.DateTimeField()),
                ('billing_period_end', models.DateTimeField()),
                ('minutes', models.IntegerField()),
                ('reason', models.CharField(choices=[('server_session', 'Server Session'), ('admin_adjustment', 'Admin Adjustment')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='processed', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_subscription_webhook_event'),
        ),
        migrations.AddField(
            model_name='usageledgerentry',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_entries', to='subscriptions.subscriptionentitlement'),
        ),
        migrations.AddField(
            model_name='usageledgerentry',
            name='server_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_entry', to='subscriptions.serversession'),
        ),
        migrations.AddField(
            model_name='usageledgerentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_usage_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionentitlement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionentitlement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_entitlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serversession',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='server_sessions', to='subscriptions.subscriptionentitlement'),
        ),
        migrations.AddField(
            model_name='serversession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_server_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usageledgerentry',
            index=models.Index(fields=['user', 'billing_period_start', 'billing_period_end'], name='subscriptio_user_id_f59e07_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionentitlement',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_f554ab_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionentitlement',
            index=models.Index(fields=['provider', 'provider_subscription_id'], name='subscriptio_provide_834861_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionentitlement',
            index=models.Index(fields=['current_period_end'], name='subscriptio_current_5d9c85_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionentitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_subscription_id', ''), _negated=True), fields=('provider', 'provider_subscription_id'), name='unique_subscription_provider_subscription'),
        ),
        migrations.AddIndex(
            model_name='serversession',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_27cd51_idx'),
        ),
        migrations.AddIndex(
            model_name='serversession',
            index=models.Index(fields=['last_heartbeat_at'], name='subscriptio_last_he_9d0fbb_idx'),
        ),
    ]
